name = "CreateNuggets"
author = "Mak0nz"
version = "26.09.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7db6deb2ccc9d931fc25ffd4f60ff445a648adc236a7afafec817d286108986e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = []
datapack-folder = "moonlight-global-datapacks"
