name = "CreateNuggets"
author = "Mak0nz"
version = "26.02.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caae36e77d137b76d7df428f113fad328f121d76ad110ea8096b93ed7e673450"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
