name: Send Release Notes to Discord

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  discord-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Release Notes to Discord
        uses: JFWenisch/discord-releasenotes-action@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          github_token: ${{ secrets.GH_TOKEN }}
